DROP DATABASE learn_hibernate;
CREATE DATABASE LEARN_HIBERNATE DEFAULT CHARACTER SET UTF8 DEFAULT COLLATE UTF8_BIN;
CREATE DATABASE LEARN_HIBERNATE DEFAULT CHARSET 'UTF8';
GRANT ALL PRIVILEGES ON LEARN_HIBERNATE.* TO root@'localhost' IDENTIFIED BY 'abbasi';
FLUSH PRIVILEGES;

use LEARN_HIBERNATE;

DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS CONFIGURATION;
DROP TABLE IF EXISTS FIRM;

CREATE TABLE FIRM
(
  FIRM_ID INTEGER AUTO_INCREMENT,
  FIRM_NAME VARCHAR(255) NOT NULL,
  PRIMARY KEY (FIRM_ID)
);

CREATE TABLE CONFIGURATION
(
  FIRM_ID INTEGER,
  PWD_SALT VARCHAR(255),
  CONFIGURATION BLOB,
  CONSTRAINT FOREIGN KEY (FIRM_ID) REFERENCES FIRM(FIRM_ID)
);

CREATE TABLE USERS
(
  FIRM_ID INTEGER,
  USERNAME VARCHAR(255),
  USER_PWD VARCHAR(255),
  USER_EMAIL VARCHAR(255),
  PRIMARY KEY (USERNAME,FIRM_ID),
  CONSTRAINT FOREIGN KEY (FIRM_ID) REFERENCES FIRM(FIRM_ID)
);