CREATE SCHEMA IF NOT EXISTS PUB1;
CREATE SCHEMA IF NOT EXISTS PUB2;

SET SCHEMA PUB1;

CREATE TABLE USER (
  USER_ID NUMERIC AUTO_INCREMENT,
  USERNAME VARCHAR(255),
  PASSWORD VARCHAR(255),
  PRIMARY KEY (USER_ID)
);

INSERT INTO USER (USERNAME, PASSWORD) VALUES ( 'pub1.user1','x' );
INSERT INTO USER (USERNAME, PASSWORD) VALUES ( 'pub1.user2','x' );
INSERT INTO USER (USERNAME, PASSWORD) VALUES ( 'pub1.user3','x' );
INSERT INTO USER (USERNAME, PASSWORD) VALUES ( 'pub1.user4','x' );


SET SCHEMA PUB2;
CREATE TABLE USER (
    USER_ID NUMERIC AUTO_INCREMENT,
    USERNAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    PRIMARY KEY (USER_ID)
);

INSERT INTO USER (USERNAME, PASSWORD) VALUES ( 'pub2.user1','x' );
INSERT INTO USER (USERNAME, PASSWORD) VALUES ( 'pub2.user2','x' );
INSERT INTO USER (USERNAME, PASSWORD) VALUES ( 'pub2.user3','x' );
INSERT INTO USER (USERNAME, PASSWORD) VALUES ( 'pub2.user4','x' );